#include<stdio.h>
#include<stdlib.h>
#include<math.h>
#include<fftw3.h>
#include"nrutil.h"
#include"nrutil.c"
int main (void)
{

 int N;
 FILE *fpt1, *fpt2, * fpt3, *fpw;
 int i, j, temp;
 fftw_complex *comp;
 double teta;
 char fn1[100], fn2[100], fn3[100], fn4[100];
 int count;
 int initial;
 int final;
 int steps;
 double delta_t = 0.01;
 double evolve_time;
 fputs("Enter the system size (N)\n",stdout);
 scanf("%d",&N);
 printf ("Initial count (initial)\n");
 scanf ("%d", &initial);
 printf ("Final count (final) \n");
 scanf ("%d", &final);
 printf ("Steps (steps) \n");
 scanf ("%d", &steps);
 comp = fftw_malloc (sizeof (fftw_complex) * N * N);
 for (count = initial; count <= final; count = count + steps) {
 sprintf (fn1, "comp.%06d", count);
 sprintf (fn4, "comp%06dc.eps",count);
 evolve_time = count * delta_t;
 
 fpt1 = fopen (fn1, "r");
 fread (&comp[0][0], sizeof(double), 2 * N * N, fpt1);
 fclose (fpt1);

  fpw = fopen (fn4, "w");
  fprintf (fpw, "%%!PS-Adobe-2.0 EPSF-2.0\n");
  fprintf (fpw, "%%%%Generated by C-Program output\n");
  fprintf (fpw, "%%%%Creator: Saswata\n");
  fprintf (fpw, "%%%%Title: Microstructure\n");
  fprintf (fpw, "%%%%BoundingBox: 0 0 100 100\n");
  fprintf (fpw, "100  0 translate\n");
  fprintf (fpw, "90 rotate\n");
  fprintf (fpw, "100 100 scale\n");
  fprintf (fpw, "/picstr  200  string def\n");
  fprintf (fpw, "200 200 8 [200 0 0 -200 0 200]\n");
  fprintf (fpw, "{currentfile picstr readhexstring pop} image\n");

  for (i = 412; i < 612; i++) {
   for (j = 412; j < 612; j++) {
    teta = comp[j + i * N][0];
    if (teta > 1.0)
     teta = 1.0;
    if (teta < 0.0)
     teta = 0.0;
     temp = (int) 255 * (1.0 - teta);
    fprintf (fpw, "%02x", temp);
   }
   fprintf (fpw, "\n");
  }

  fprintf (fpw, "grestore\n");
  fprintf (fpw, "showpage\n");
  fprintf (fpw, "%%%%EOF\n");
  fclose (fpw);
 }
 system ("mkdir EPS");
 system ("mv *.eps EPS/");
 fftw_free (comp);
 return(0);
}
