#include<stdio.h>
#include<stdlib.h>
#include<math.h>
#include<fftw3.h>
#include"gsl_support.h"
#include"gsl_support.c"
int main (void)
{

 int N;
 FILE *fpt1, *fpt2, * fpt3, *fpw;
 int i, j, t1, t2, tempr, tempg, templ;
 fftw_complex *eta_1, *eta_2, *eta_3;
 double eta1, eta2, eta3, teta;
 int temp;
 char fn1[100], fn2[100], fn3[100], fn4[100];
 int count;
 int initial;
 int final;
 int steps;
 double delta_t = 0.01;
 double evolve_time;
 fputs("Enter the system size (N)\n",stdout);
 scanf("%d",&N);
 printf ("Initial count (initial)\n");
 scanf ("%d", &initial);
 printf ("Final count (final) \n");
 scanf ("%d", &final);
 printf ("Steps (steps) \n");
 scanf ("%d", &steps);
 eta_1 = fftw_malloc (sizeof (fftw_complex) * N * N);
 eta_2 = fftw_malloc (sizeof (fftw_complex) * N * N);
 eta_3 = fftw_malloc (sizeof (fftw_complex) * N * N);
 for (count = initial; count <= final; count = count + steps) {
 sprintf (fn1, "eta1.%06d", count);
 sprintf (fn2, "eta2.%06d", count);
 sprintf (fn3, "eta3.%06d", count);
 sprintf (fn4, "eta%06dc.eps",count);
  evolve_time = count * delta_t;
//  sprintf (fn1, "eta1.%07.2f", evolve_time);
//  sprintf (fn2, "eta2.%07.2f", evolve_time);
//  sprintf (fn3, "eta3.%07.2f", evolve_time);
//  sprintf (fn4, "eta%07.2f.eps",evolve_time);
  fpt1 = fopen (fn1, "r");
  fpt2 = fopen (fn2, "r");
  fpt3 = fopen (fn3, "r");

  fread (&eta_1[0][0], sizeof(double), 2 * N * N, fpt1);
  fread (&eta_2[0][0], sizeof(double), 2 * N * N, fpt2);
  fread (&eta_3[0][0], sizeof(double), 2 * N * N, fpt3);

  fclose (fpt1);
  fclose (fpt2);
  fclose (fpt3);

  fpw = fopen (fn4, "w");
  fprintf (fpw, "%%!PS-Adobe-2.0 EPSF-2.0\n");
  fprintf (fpw, "%%%%Generated by C-Program output\n");
  fprintf (fpw, "%%%%Creator: Saswata\n");
  fprintf (fpw, "%%%%Title: Microstructure\n");
  fprintf (fpw, "%%%%BoundingBox: 0 0 %d %d\n", N/4, N/4);
  fprintf (fpw, "%d  0 translate\n", N/4);
  fprintf (fpw, "90 rotate\n");
  fprintf (fpw, "%d %d scale\n", N/4, N/4);
  fprintf (fpw, "/picstr %d string def\n", N);
  fprintf (fpw, "%d %d 8 [%d 0 0 -%d 0 %d]\n", N, N, N, N, N);
  fprintf (fpw, "{currentfile picstr readhexstring pop} image\n");

  for (i = 0; i < N; i++) {
   for (j = 0; j < N; j++) {
    eta1 = eta_1[j + i * N][0];
    eta2 = eta_2[j + i * N][0];
    eta3 = eta_3[j + i * N][0];
		teta = ((eta1 * eta1) - (eta2 * eta2) - (2.0 * eta3 * eta3) + 2.0)/3.0;
    if (teta > 1.0)
    teta = 1.0;
    if (teta < 0.0)
    teta = 0.0;
     
     temp = (int) 255 * teta;



    fprintf (fpw, "%02x", temp);
   }
   fprintf (fpw, "\n");
  }

  fprintf (fpw, "grestore\n");
  fprintf (fpw, "showpage\n");
  fprintf (fpw, "%%%%EOF\n");
  fclose (fpw);
 }
 system ("mkdir EPS");
 system ("mv *.eps EPS/");
 fftw_free (eta_1);
 fftw_free (eta_2);
 fftw_free (eta_3);
 return(0);
}
